### ISSUE TITLE
Licence unspecified

### ISSUE THREAD

**Issue by shirakaba** [halfnelson/nativescript-source-to-jsx-def#6]
Could you please specify a licence?

**Comment by halfnelson** [comment]
Went with MIT,
added apache 2 license for reference but since it says
```
Derivative Works shall not include works that remain
      separable from, or merely link (or bind by name) to the interfaces of,
      the Work and Derivative Works thereof.
```
then I am pretty sure the generated JSX is not under Apache2 license and will be under the MIT

**Comment by shirakaba** [comment]
Good spot! Sounds convincing. I think you've gone with a good approach; thanks for the extra attention.
