### ISSUE TITLE
Distributing a copy with minor alterations for consumption by React NativeScript

### ISSUE THREAD

**Issue by shirakaba** [halfnelson/nativescript-source-to-jsx-def#8]
For React NativeScript to be able to consume these typings directly on each version of NativeScript without alteration, it would be really handy to have a minor alteration of `sveltenative-jsx.d.ts` distributed: `react-nativescript-jsx.ts` . The only differences would be:

* All `Attributes` interfaces are exported (no need to re-export the imports at the top of the file)
* The file extension is `.ts` rather than `.d.ts`
* Properties preserve the casing used by the JS setters (see #7)
* Event handlers are spelt with camel-casing, e.g. `onDoubleTap` (see #7)

**Comment by halfnelson** [comment]
PR was merged
